name: ChestLocker
main: ChestLocker\Main
version: "1.2"
api: 5.0.0
load: STARTUP
author: EvolSoft
description: Lock/Unlock Chests.
website: https://www.evolsoft.tk

permissions:
  chestlocker.bypass:
    default: op
    description: ""
  cmd.unlockchest:
    default: true
    description: ""
  cmd.lockchest:
    default: true
    description: ""
  cmd.chestlocker.help:
    default: op
    description: ""
  cmd.chestlocker.reload:
    default: op
    description: ""
  cmd.chestlocker.info:
    default: op
    description: ""
  cmd.chestlocker:
    default: true
    description: ""
